"use client"

import { Check, Download, FileText, Save } from "lucide-react"

import { useApp } from "@/components/app-store"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import type { DiseaseResult } from "@/lib/targets-data"

export function DocumentView({ result }: { result: DiseaseResult }) {
  const { saveCurrentReport, activeReportId } = useApp()

  const top = result.targets.slice(0, 3)
  const topNames = top.map((t) => t.symbol)
  const smallMolecules = result.targets.filter(
    (t) => t.modality === "Small Molecule",
  ).length
  const antibodies = result.targets.length - smallMolecules
  const topResource = mostCommon(result.targets.map((t) => t.resource))

  return (
    <div className="flex flex-col gap-6">
      <Card>
        <CardContent className="flex flex-col gap-8 px-6 py-8 md:px-10 md:py-10">
          {/* Title block */}
          <header className="flex flex-col gap-2 border-b border-border pb-6">
            <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-primary">
              <FileText className="size-4" />
              Target Identification Report
            </div>
            <h2 className="text-2xl font-semibold tracking-tight text-foreground">
              {result.disease}
            </h2>
            <p className="text-sm text-muted-foreground">
              Generated by Targetly AI ·{" "}
              {new Date().toLocaleDateString(undefined, {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </p>
          </header>

          {/* Executive Summary */}
          <section className="flex flex-col gap-3">
            <h3 className="text-base font-semibold text-foreground">
              Executive Summary
            </h3>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Targetly analyzed multi-omic evidence for{" "}
              <span className="font-medium text-foreground">
                {result.disease}
              </span>{" "}
              and prioritized{" "}
              <span className="font-medium text-foreground">
                {result.targets.length} candidate targets
              </span>
              . The strongest associations are{" "}
              <span className="font-medium text-foreground">
                {topNames.join(", ")}
              </span>
              , each supported by convergent genetic and functional evidence. Of
              the prioritized set, {smallMolecules} are tractable via small
              molecules and {antibodies} are amenable to antibody-based
              modalities. The dominant line of evidence across this target set is{" "}
              <span className="font-medium text-foreground">{topResource}</span>
              , suggesting a coherent biological mechanism worth pursuing in
              early discovery.
            </p>
          </section>

          <Separator />

          {/* Top Targets */}
          <section className="flex flex-col gap-4">
            <h3 className="text-base font-semibold text-foreground">
              Top Targets
            </h3>
            <div className="flex flex-col gap-4">
              {top.map((t, i) => (
                <div key={t.symbol} className="flex flex-col gap-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-mono text-sm font-semibold text-foreground">
                      {i + 1}. {t.symbol}
                    </span>
                    <Badge variant="secondary">{t.modality}</Badge>
                    <Badge variant="outline">{t.resource}</Badge>
                    <span className="ml-auto text-xs font-medium text-muted-foreground">
                      Score {t.score.toFixed(2)}
                    </span>
                  </div>
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    <span className="font-medium text-foreground">{t.name}</span>{" "}
                    ranks among the highest-confidence candidates, with{" "}
                    {t.resource.toLowerCase()} evidence driving its association
                    score of {t.score.toFixed(2)}. It is currently best
                    addressed through a {t.modality.toLowerCase()} approach.
                  </p>
                </div>
              ))}
            </div>
          </section>

          <Separator />

          {/* Supporting Literature */}
          <section className="flex flex-col gap-4">
            <h3 className="text-base font-semibold text-foreground">
              Supporting Literature
            </h3>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Key findings synthesized from {result.papers.length} relevant
              publications:
            </p>
            <ul className="flex flex-col gap-3">
              {result.papers.map((p) => (
                <li key={p.title} className="flex flex-col gap-1">
                  <p className="text-sm font-medium leading-snug text-foreground">
                    {p.title}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    {p.journal} · {p.year} · implicates {p.targets.join(", ")}
                  </p>
                </li>
              ))}
            </ul>
          </section>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-sm">Export</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col gap-3 sm:flex-row">
          <Button
            variant="outline"
            onClick={() => window.print()}
            className="flex-1"
          >
            <Download data-icon="inline-start" />
            Download as PDF
          </Button>
          <Button
            onClick={saveCurrentReport}
            disabled={Boolean(activeReportId)}
            className="flex-1"
          >
            {activeReportId ? (
              <>
                <Check data-icon="inline-start" />
                Saved to Reports
              </>
            ) : (
              <>
                <Save data-icon="inline-start" />
                Save to Reports
              </>
            )}
          </Button>
        </CardContent>
      </Card>
    </div>
  )
}

function mostCommon(items: string[]) {
  const counts = new Map<string, number>()
  for (const item of items) counts.set(item, (counts.get(item) ?? 0) + 1)
  let best = items[0] ?? ""
  let bestCount = 0
  for (const [item, count] of counts) {
    if (count > bestCount) {
      best = item
      bestCount = count
    }
  }
  return best
}
