"use client"

import * as React from "react"
import { Check, Download, FileText, Loader2, Save } from "lucide-react"

import { useApp } from "@/components/app-store"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import type { ScoreResponse } from "@/lib/api"
import { stageLabel } from "@/lib/opentargets"
import {
  buildReportData,
  downloadReportHtml,
  type TargetReportSection,
} from "@/lib/report"

export function DocumentView({ result }: { result: ScoreResponse }) {
  const { saveCurrentReport, activeReportId } = useApp()
  const [sections, setSections] = React.useState<TargetReportSection[] | null>(
    null,
  )
  const [loading, setLoading] = React.useState(true)

  React.useEffect(() => {
    let active = true
    setLoading(true)
    buildReportData(result)
      .then((data) => {
        if (active) setSections(data)
      })
      .catch((err) => {
        console.error("Failed to build report data:", err)
        if (active) setSections([])
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [result])

  const top = [...result.targets].sort((a, b) => b.score - a.score).slice(0, 3)
  const topNames = top.map((t) => t.symbol)
  const avgTractability =
    result.targets.reduce((sum, t) => sum + t.tractability, 0) /
    Math.max(result.targets.length, 1)
  const topEvidenceType = mostCommonEvidence(result.targets)

  const totalDrugs = sections?.reduce((s, x) => s + x.drugs.length, 0) ?? 0
  const totalRefs = sections?.reduce((s, x) => s + x.literature.length, 0) ?? 0

  function handleDownload() {
    if (!sections) return
    downloadReportHtml(result, sections)
  }

  return (
    <div className="flex flex-col gap-6">
      <Card>
        <CardContent className="flex flex-col gap-8 px-6 py-8 md:px-10 md:py-10">
          {/* Title block */}
          <header className="flex flex-col gap-2 border-b border-border pb-6">
            <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-primary">
              <FileText className="size-4" />
              Target Identification Report
            </div>
            <h2 className="text-2xl font-semibold tracking-tight text-foreground">
              {result.disease_label}
            </h2>
            <p className="text-sm text-muted-foreground">
              Generated by MentyTarget &middot;{" "}
              {new Date().toLocaleDateString(undefined, {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
              {" "}&middot; Model: {result.model}
            </p>
          </header>

          {/* Executive Summary */}
          <section className="flex flex-col gap-3">
            <h3 className="text-base font-semibold text-foreground">
              Executive Summary
            </h3>
            <p className="text-sm leading-relaxed text-muted-foreground">
              MentyTarget analyzed multi-omic evidence for{" "}
              <span className="font-medium text-foreground">
                {result.disease_label}
              </span>{" "}
              and prioritized{" "}
              <span className="font-medium text-foreground">
                {result.targets.length} candidate targets
              </span>{" "}
              for a {result.modality.replace(/_/g, " ")} approach. The
              strongest associations are{" "}
              <span className="font-medium text-foreground">
                {topNames.join(", ")}
              </span>
              , each supported by convergent evidence. The average
              tractability across this target set is{" "}
              <span className="font-medium text-foreground">
                {avgTractability.toFixed(2)}
              </span>
              , with{" "}
              <span className="font-medium text-foreground">
                {topEvidenceType}
              </span>{" "}
              as the dominant evidence type, suggesting a coherent
              biological mechanism worth pursuing in early discovery.
            </p>
          </section>

          <Separator />

          {/* Full target dossier */}
          <section className="flex flex-col gap-4">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h3 className="text-base font-semibold text-foreground">
                Targets, Drugs &amp; Supporting Literature
              </h3>
              {sections && (
                <div className="flex gap-2">
                  <Badge variant="secondary">{sections.length} targets</Badge>
                  <Badge variant="secondary">{totalDrugs} drugs</Badge>
                  <Badge variant="secondary">{totalRefs} references</Badge>
                </div>
              )}
            </div>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Every prioritized target below is paired with its known compounds
              (Open Targets) and the recent publications it draws on (Europe
              PMC). The downloadable report contains this same full dossier.
            </p>

            {loading && (
              <div className="flex flex-col gap-4">
                {[0, 1, 2].map((i) => (
                  <Skeleton key={i} className="h-32 w-full rounded-lg" />
                ))}
              </div>
            )}

            {!loading && sections && (
              <div className="flex flex-col gap-4">
                {sections.map((s, i) => (
                  <TargetDossier key={s.target.target_id} section={s} index={i} />
                ))}
              </div>
            )}
          </section>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-sm">Export</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col gap-3 sm:flex-row">
          <Button
            variant="outline"
            onClick={handleDownload}
            disabled={loading || !sections}
            className="flex-1"
          >
            {loading ? (
              <>
                <Loader2 data-icon="inline-start" className="animate-spin" />
                Preparing full report…
              </>
            ) : (
              <>
                <Download data-icon="inline-start" />
                Download full report
              </>
            )}
          </Button>
          <Button
            onClick={saveCurrentReport}
            disabled={Boolean(activeReportId)}
            className="flex-1"
          >
            {activeReportId ? (
              <>
                <Check data-icon="inline-start" />
                Saved to Reports
              </>
            ) : (
              <>
                <Save data-icon="inline-start" />
                Save to Reports
              </>
            )}
          </Button>
        </CardContent>
      </Card>
    </div>
  )
}

function TargetDossier({
  section,
  index,
}: {
  section: TargetReportSection
  index: number
}) {
  const { target: t, drugs, literature } = section

  return (
    <div className="flex flex-col gap-3 rounded-lg border bg-card px-4 py-4">
      <div className="flex flex-wrap items-center gap-2">
        <span className="font-mono text-sm font-semibold text-foreground">
          {index + 1}. {t.symbol}
        </span>
        <span className="text-xs text-muted-foreground">{t.name}</span>
        <span className="ml-auto text-xs font-medium text-muted-foreground">
          Score {t.score.toFixed(2)}
        </span>
      </div>

      <div className="flex flex-wrap gap-1">
        {t.evidence.map((e) => (
          <Badge key={e.datatype} variant="outline">
            {e.datatype.replace(/_/g, " ")}
          </Badge>
        ))}
      </div>

      <p className="text-sm leading-relaxed text-muted-foreground">
        {t.explanation}
      </p>

      <div className="flex flex-col gap-2">
        <h4 className="text-xs font-semibold uppercase tracking-wide text-primary">
          Suggested drugs ({drugs.length})
        </h4>
        {drugs.length > 0 ? (
          <div className="flex flex-wrap gap-1.5">
            {drugs.slice(0, 12).map((d) => (
              <Badge
                key={d.drugId}
                variant="secondary"
                className="font-normal"
                title={d.mechanismOfAction ?? d.drugType ?? undefined}
              >
                {d.prefName}
                <span className="ml-1 text-muted-foreground">
                  · {stageLabel(d.stage)}
                </span>
              </Badge>
            ))}
            {drugs.length > 12 && (
              <Badge variant="outline" className="font-normal">
                +{drugs.length - 12} more
              </Badge>
            )}
          </div>
        ) : (
          <p className="text-xs text-muted-foreground">
            No known drugs recorded — potential novel opportunity.
          </p>
        )}
      </div>

      <div className="flex flex-col gap-2">
        <h4 className="text-xs font-semibold uppercase tracking-wide text-primary">
          Supporting literature ({literature.length})
        </h4>
        {literature.length > 0 ? (
          <ol className="flex flex-col gap-1.5 pl-4">
            {literature.map((l) => (
              <li key={l.id} className="list-decimal text-sm text-muted-foreground">
                <a
                  href={l.url}
                  target="_blank"
                  rel="noreferrer"
                  className="text-primary hover:underline"
                >
                  {l.title}
                </a>
                {l.journal ? ` — ${l.journal}` : ""}
                {l.year ? ` (${l.year})` : ""}
                {l.pmid ? ` · PMID ${l.pmid}` : ""}
              </li>
            ))}
          </ol>
        ) : (
          <p className="text-xs text-muted-foreground">
            No indexed publications found for this target.
          </p>
        )}
      </div>
    </div>
  )
}

function mostCommonEvidence(targets: ScoreResponse["targets"]): string {
  const counts = new Map<string, number>()
  for (const t of targets) {
    for (const e of t.evidence) {
      counts.set(e.datatype, (counts.get(e.datatype) ?? 0) + 1)
    }
  }
  let best = "genetic_association"
  let bestCount = 0
  for (const [item, count] of counts) {
    if (count > bestCount) {
      best = item
      bestCount = count
    }
  }
  return best.replace(/_/g, " ")
}
