"use client"

import { Check, Download, FileText, Save } from "lucide-react"

import { useApp } from "@/components/app-store"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { downloadReportPdf } from "@/lib/api"
import type { ScoreResponse } from "@/lib/api"

export function DocumentView({ result }: { result: ScoreResponse }) {
  const { saveCurrentReport, activeReportId } = useApp()

  const top = [...result.targets].sort((a, b) => b.score - a.score).slice(0, 3)
  const topNames = top.map((t) => t.symbol)
  // Every prioritized target that has at least one linked publication, ranked.
  const targetsWithLiterature = [...result.targets]
    .sort((a, b) => a.rank - b.rank)
    .filter((t) => t.literature.length > 0)
  const avgTractability =
    result.targets.reduce((sum, t) => sum + t.tractability, 0) /
    Math.max(result.targets.length, 1)
  const topEvidenceType = mostCommonEvidence(result.targets)

  async function handleDownload() {
    try {
      const blob = await downloadReportPdf(
        result.disease_label,
        result.modality,
        result.targets,
      )
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `mentytarget_${result.disease_label.replace(/\s+/g, "_")}.pdf`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error("Failed to download report:", err)
    }
  }

  return (
    <div className="flex flex-col gap-6">
      <Card>
        <CardContent className="flex flex-col gap-8 px-6 py-8 md:px-10 md:py-10">
          {/* Title block */}
          <header className="flex flex-col gap-2 border-b border-border pb-6">
            <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-primary">
              <FileText className="size-4" />
              Target Identification Report
            </div>
            <h2 className="text-2xl font-semibold tracking-tight text-foreground">
              {result.disease_label}
            </h2>
            <p className="text-sm text-muted-foreground">
              Generated by MentyTarget &middot;{" "}
              {new Date().toLocaleDateString(undefined, {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
              {" "}&middot; Model: {result.model}
            </p>
          </header>

          {/* Executive Summary */}
          <section className="flex flex-col gap-3">
            <h3 className="text-base font-semibold text-foreground">
              Executive Summary
            </h3>
            <p className="text-sm leading-relaxed text-muted-foreground">
              MentyTarget analyzed multi-omic evidence for{" "}
              <span className="font-medium text-foreground">
                {result.disease_label}
              </span>{" "}
              and prioritized{" "}
              <span className="font-medium text-foreground">
                {result.targets.length} candidate targets
              </span>{" "}
              for a {result.modality.replace(/_/g, " ")} approach. The
              strongest associations are{" "}
              <span className="font-medium text-foreground">
                {topNames.join(", ")}
              </span>
              , each supported by convergent evidence. The average
              tractability across this target set is{" "}
              <span className="font-medium text-foreground">
                {avgTractability.toFixed(2)}
              </span>
              , with{" "}
              <span className="font-medium text-foreground">
                {topEvidenceType}
              </span>{" "}
              as the dominant evidence type, suggesting a coherent
              biological mechanism worth pursuing in early discovery.
            </p>
          </section>

          <Separator />

          {/* Top Targets */}
          <section className="flex flex-col gap-4">
            <h3 className="text-base font-semibold text-foreground">
              Top Targets
            </h3>
            <div className="flex flex-col gap-4">
              {top.map((t, i) => (
                <div key={t.target_id} className="flex flex-col gap-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-mono text-sm font-semibold text-foreground">
                      {i + 1}. {t.symbol}
                    </span>
                    {t.evidence.map((e) => (
                      <Badge key={e.datatype} variant="outline">
                        {e.datatype.replace(/_/g, " ")}
                      </Badge>
                    ))}
                    <span className="ml-auto text-xs font-medium text-muted-foreground">
                      Score {t.score.toFixed(2)}
                    </span>
                  </div>
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    <span className="font-medium text-foreground">{t.name}</span>{" "}
                    {t.explanation}
                  </p>
                </div>
              ))}
            </div>
          </section>

          <Separator />

          {/* Supporting Literature */}
          <section className="flex flex-col gap-4">
            <h3 className="text-base font-semibold text-foreground">
              Supporting Literature
            </h3>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Key publications linking the prioritized targets to{" "}
              {result.disease_label}:
            </p>
            {targetsWithLiterature.length > 0 ? (
              <div className="flex flex-col gap-5">
                {targetsWithLiterature.map((t) => (
                  <div key={t.target_id} className="flex flex-col gap-2">
                    <p className="font-mono text-sm font-semibold text-foreground">
                      {t.symbol}
                      <span className="ml-2 font-sans text-xs font-normal text-muted-foreground">
                        Rank #{t.rank}
                      </span>
                    </p>
                    <ul className="flex flex-col gap-2 border-l border-border pl-4">
                      {t.literature.map((lit) => (
                        <li
                          key={`${t.target_id}-${lit.pubmed_id}`}
                          className="flex flex-col gap-0.5"
                        >
                          <p className="text-sm leading-snug text-muted-foreground">
                            {lit.year ? `Published ${lit.year}` : "Publication"}
                          </p>
                          {lit.pubmed_id && (
                            <a
                              href={`https://pubmed.ncbi.nlm.nih.gov/${lit.pubmed_id}/`}
                              target="_blank"
                              rel="noreferrer"
                              className="text-xs text-primary hover:underline"
                            >
                              PubMed ID: {lit.pubmed_id}
                            </a>
                          )}
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm leading-relaxed text-muted-foreground">
                No linked publications were returned for this target set.
              </p>
            )}
          </section>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-sm">Export</CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col gap-3 sm:flex-row">
          <Button
            variant="outline"
            onClick={handleDownload}
            className="flex-1"
          >
            <Download data-icon="inline-start" />
            Download as PDF
          </Button>
          <Button
            onClick={saveCurrentReport}
            disabled={Boolean(activeReportId)}
            className="flex-1"
          >
            {activeReportId ? (
              <>
                <Check data-icon="inline-start" />
                Saved to Reports
              </>
            ) : (
              <>
                <Save data-icon="inline-start" />
                Save to Reports
              </>
            )}
          </Button>
        </CardContent>
      </Card>
    </div>
  )
}

function mostCommonEvidence(targets: ScoreResponse["targets"]): string {
  const counts = new Map<string, number>()
  for (const t of targets) {
    for (const e of t.evidence) {
      counts.set(e.datatype, (counts.get(e.datatype) ?? 0) + 1)
    }
  }
  let best = "genetic_association"
  let bestCount = 0
  for (const [item, count] of counts) {
    if (count > bestCount) {
      best = item
      bestCount = count
    }
  }
  return best.replace(/_/g, " ")
}
